name: build

on:
  workflow_dispatch:
  push:
    branches:
      - github_build

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build docker image
      run: |
        make docker-build