name: release

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 50

    - name: Create release branch.
      run: |
        make create-release-branch
